import test from 'node:test';
import assert from 'node:assert/strict';
import {validateContact,emailPayload} from '../lib/contact';
import {POST} from '../app/api/contact/route';
const input={name:'Test Visitor',email:'visitor@example.org',message:'This is a local delivery-handler test.',startedAt:Date.now()-5000,website:''};
function request(body:unknown=input,origin='https://portfolio.example'){return new Request('https://portfolio.example/api/contact',{method:'POST',headers:{origin,'Content-Type':'application/json','x-forwarded-for':'192.0.2.1'},body:JSON.stringify(body)});}
test('Rejects header injection and oversized input',()=>{assert.equal(validateContact({...input,email:'a@example.org\r\nBcc: attacker@example.org'}),null);assert.equal(validateContact({...input,name:'X\nInjected'}),null);assert.equal(validateContact({...input,message:'x'.repeat(5001)}),null);});
test('Recipient and sender are server-controlled, visitor gets Reply-To',()=>{const p=emailPayload(input,'owner@example.org','sender@example.org');assert.deepEqual(p.to,['owner@example.org']);assert.equal(p.from,'sender@example.org');assert.equal(p.reply_to,input.email);});
test('Rejects cross-origin and honeypot submissions',async()=>{assert.equal((await POST(request(input,'https://unrelated.example'))).status,403);assert.equal((await POST(request({...input,website:'spam'}))).status,400);});
test('Missing configuration never claims delivery',async()=>{const old=process.env.RESEND_API_KEY;delete process.env.RESEND_API_KEY;try{const r=await POST(request());assert.equal(r.status,503);assert.match((await r.json()).error,/not configured/);}finally{if(old)process.env.RESEND_API_KEY=old;}});
test('Delivery success and provider failure handled truthfully (mocked provider)',async()=>{const oldKey=process.env.RESEND_API_KEY,oldFrom=process.env.CONTACT_FROM,oldFetch=global.fetch;process.env.RESEND_API_KEY='local-test-not-a-real-key';process.env.CONTACT_FROM='sender@example.org';try{let payload:any;global.fetch=async(_url,options)=>{payload=JSON.parse(String(options?.body));return Response.json({id:'mock-receipt'});};const response=await POST(request());assert.equal(response.status,200);assert.deepEqual(payload.to,['binyaminmughal@outlook.com']);assert.equal(payload.reply_to,input.email);global.fetch=async()=>Response.json({error:'provider unavailable'},{status:503});assert.equal((await POST(request())).status,502);}finally{global.fetch=oldFetch;if(oldKey)process.env.RESEND_API_KEY=oldKey;else delete process.env.RESEND_API_KEY;if(oldFrom)process.env.CONTACT_FROM=oldFrom;else delete process.env.CONTACT_FROM;}});
